// src/mastra/agents/coach-agent/github-tool.ts

import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import { createRepoAndPush } from "./octokit-helper"; // 👈 uses Octokit abstraction

export const githubTool = createTool({
    id: "github-tool",
    description: "Creates a GitHub repository and adds a README file",
    inputSchema: z.object({
        name: z.string().describe("Repository name"),
        private: z.boolean().describe("Make repo private?"),
    }),
    outputSchema: z.object({
        url: z.string(),
        readmeUrl: z.string(),
    }),
    execute: async ({ context }) => {
        const { name, private: isPrivate } = context;

        // Optional: Customize README content
        const readmeContent = `# ${name}\nGenerated by CoachAgent`;

        // Use Octokit helper
        return await createRepoAndPush(name, isPrivate, readmeContent);
    },
});
