// src/mastra/agents/coach-agent/octokit-helper.ts
import { Octokit } from "@octokit/rest";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

export const createRepoAndPush = async (
    repoName: string,
    isPrivate: boolean,
    readmeContent: string = ""
) => {
    // 1. Create Repo
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        private: isPrivate,
    });

    // 2. Add README.md
    await octokit.repos.createOrUpdateFileContents({
        owner: repo.owner.login,
        repo: repo.name,
        path: "README.md",
        message: "chore: add README",
        content: Buffer.from(readmeContent || `# ${repoName}\nGenerated by CoachAgent`).toString("base64"),
    });

    return {
        url: repo.html_url,
        readmeUrl: `${repo.html_url}/blob/main/README.md`,
    };
};
